spring:
  application:
    name: zuul
    
  rabbitmq:
    host: 192.168.247.132
    port: 5672
    username: admin
    password: admin  
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
zuul:
  retryable: true

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream            